services:
  - type: web
    name: visimo-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
